# Generated by Django 4.2.23 on 2025-08-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onnanoko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_self_registration', models.BooleanField(default=True)),
            ],
        ),
    ]
