# Generated by Django 4.2.23 on 2025-08-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onnanoko', '0002_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='illustrator',
            field=models.CharField(blank=True, help_text='Name of the artist/illustrator', max_length=128),
        ),
    ]
